#app:
#  jwt:
#    secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9u
#    expiration: 3600000
#    refresh-expiration: 6400000
#
#spring:
#  application:
#    name: auth-service
#  liquibase:
#    enabled: false
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    test-rollback-on-update: true
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5433/healthcare_db}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8080

#keycloak:
#  realm: mths
#  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9082}
#  client-id: mths-id
#  client-secret: ${KEYCLOAK_CLIENT_SECRET}




app:
  jwt:
    secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9u
    expiration: 3600000
    refresh-expiration: 6400000

spring:
  application:
    name: auth-service
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    test-rollback-on-update: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthcare_db}
    username: postgres
    password: mechack200
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ← Changed from create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081  # ← Fixed from 808