#
#
#version: '3'
#services:
#  postgres:
#    image: postgres:latest
#    restart: always
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: healthcare_db
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#    ports:
#      - "5433:5432"
#    networks:
#      - local
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:25.0.0
#    command: start-dev
#    restart: always
#    depends_on:
#      - postgres
#      - mailhog
#    ports:
#      - "9082:8080"
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_SCHEMA: public
#      KC_DB_USERNAME: admin
#      KC_DB_PASSWORD: admin
#      KC_DB_URL: jdbc:postgresql://postgres:5432/healthcare_db
#      KC_HOSTNAME: localhost
#      KC_FEATURES: token-exchange,admin-fine-grained-authz
#    networks:
#      - local
#
#  mailhog:
#    image: mailhog/mailhog:latest
#    ports:
#      - "8025:8025"
#      - "1025:1025"
#    networks:
#      - local
#
#networks:
#  local:


version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    depends_on:
      - postgres
      - mailhog
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - local
